<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
    xmlns:tns="http://api.jeroboam.com/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    name="Basic"
    targetNamespace="http://api.jeroboam.com/">
    <wsdl:types/>
  <wsdl:message name="loginRequest">
  	<wsdl:part name="userLogin" type="xsd:string"></wsdl:part>
  	<wsdl:part name="userPwd" type="xsd:string"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="loginResponse">
  	<wsdl:part name="requestId" type="xsd:integer"></wsdl:part>
  	<wsdl:part name="sessionAuthId" type="xsd:string"></wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Basic">
    <wsdl:operation name="login">
    	<wsdl:input message="tns:loginRequest"></wsdl:input>
    	<wsdl:output message="tns:loginResponse"></wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicSOAP"
  	type="tns:Basic">
  	<soap:binding style="rpc"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="login">
  		<soap:operation
  			soapAction="http://api.jeroboam.com/login" />
  		<wsdl:input>
  			<soap:body use="literal"
  				namespace="http://api.jeroboam.com/" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal"
  				namespace="http://api.jeroboam.com/" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Basic">
    <wsdl:documentation>

                         MobiquiThings, Inc.
                Copyright 2020 All Rights Reserved.

    These computer program listings and specifications, herein,
    are the property of MobiquiThings, Inc. and shall not be
    reproduced or copied or used in whole or in part as the basis
    for manufacture or sale of items without written permission.

    Basic SOAP API v1.0

    </wsdl:documentation>
    <wsdl:port binding="tns:BasicSOAP" name="BasicSOAP">
      <soap:address location="http://api.jeroboam.com/soap?service=Basic"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
