
package com.jeroboam.api;

import java.math.BigInteger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M4
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Basic", targetNamespace = "http://api.jeroboam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Basic {


    /**
     * 
     * @param userLogin
     * @param requestId
     * @param sessionAuthId
     * @param userPwd
     */
    @WebMethod(action = "http://api.jeroboam.com/login")
    public void login(
        @WebParam(name = "userLogin", partName = "userLogin")
        String userLogin,
        @WebParam(name = "userPwd", partName = "userPwd")
        String userPwd,
        @WebParam(name = "requestId", mode = WebParam.Mode.OUT, partName = "requestId")
        Holder<BigInteger> requestId,
        @WebParam(name = "sessionAuthId", mode = WebParam.Mode.OUT, partName = "sessionAuthId")
        Holder<String> sessionAuthId);

}
