
package com.jeroboam.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * 
 * 
 *                          MobiquiThings, Inc.
 *                 Copyright 2020 All Rights Reserved.
 * 
 *     These computer program listings and specifications, herein,
 *     are the property of MobiquiThings, Inc. and shall not be
 *     reproduced or copied or used in whole or in part as the basis
 *     for manufacture or sale of items without written permission.
 * 
 *     Basic SOAP API v1.0
 * 
 *     
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M4
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Basic", targetNamespace = "http://api.jeroboam.com/", wsdlLocation = "file:/Users/jerome/tmp/clojure/api-jeroboam-com/resources/wsdl/Basic.wsdl")
public class Basic_Service
    extends Service
{

    private final static URL BASIC_WSDL_LOCATION;
    private final static WebServiceException BASIC_EXCEPTION;
    private final static QName BASIC_QNAME = new QName("http://api.jeroboam.com/", "Basic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/jerome/tmp/clojure/api-jeroboam-com/resources/wsdl/Basic.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASIC_WSDL_LOCATION = url;
        BASIC_EXCEPTION = e;
    }

    public Basic_Service() {
        super(__getWsdlLocation(), BASIC_QNAME);
    }

    public Basic_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASIC_QNAME, features);
    }

    public Basic_Service(URL wsdlLocation) {
        super(wsdlLocation, BASIC_QNAME);
    }

    public Basic_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASIC_QNAME, features);
    }

    public Basic_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Basic_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Basic
     */
    @WebEndpoint(name = "BasicSOAP")
    public Basic getBasicSOAP() {
        return super.getPort(new QName("http://api.jeroboam.com/", "BasicSOAP"), Basic.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns Basic
     */
    @WebEndpoint(name = "BasicSOAP")
    public Basic getBasicSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jeroboam.com/", "BasicSOAP"), Basic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASIC_EXCEPTION!= null) {
            throw BASIC_EXCEPTION;
        }
        return BASIC_WSDL_LOCATION;
    }

}
